### PR TITLE
Remove Bower / Update to BS4

### PR DESCRIPTION
**Pull request by devotox**

### CODE REVIEW

**Comment by AmilKey** [comment]
@vsymguysung Do you plan to merge this request?

**Comment by vsymguysung** [comment]
Thanks for the contribution. 👍

**Comment by bmaehr** [comment]
@devotox Sorry to say, but I don't like you merge request. With your MR you fix the Bootstrap version to 4 and it is always included. Before it was possible to use Bootstrap 3 with Summernote. 

The problem of https://github.com/vsymguysung/ember-cli-summernote/issues/35 occures because of this change.
@AmilKey Do you have perhaps a solution to make this configurable? We use ember-bootstrap configured to 3. Perhaps it is possible to make a similar configuration for this component.

**Comment by bmaehr** [comment]
@vsymguysung After long reasearch I have a suggestion to fix your project for bootstrap 3. 
I would suggest that you release the same thing released as 1.5.2 as 1.6.0 again (working with bootstrap 4)
Then I could provide you a patch to make your sources to compile without bower and supporting bootstrap 3 and you release this as 1.5.3. 
Then there are a working bootstrap 4 (1.6.x) and a working bootstrap 3 (1.5.3) version.
Even updates of summernote for bootstarp 3 are possible without new release by overriding the package.json on customer side with the new version number.

**Comment by ghost** [comment]
@bmaehr what if you fork the project patch to BS3 and pull from your GitHub patch?

**Comment by bmaehr** [comment]
@devonte-babylon Then I have to setup an additional repository, the version will not be available with npm and others with the same problem can't use it. 
Just to make clear: The project was supporting BS3 until 1.5.0 - just 1.5.1 broke it. But at the same time 1.5.1 was the first version not needing bower.

**Pull request merged**
